"""empty message

Revision ID: 0740b141d0d0
Revises: 7fc45ad215e6
Create Date: 2018-05-09 14:08:34.650255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0740b141d0d0'
down_revision = '7fc45ad215e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('sheet_url', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'sheet_url')
    # ### end Alembic commands ###
