"""empty message

Revision ID: 1da3e560b850
Revises: 0740b141d0d0
Create Date: 2018-06-05 10:20:09.102291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da3e560b850'
down_revision = '0740b141d0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musicinstrument',
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.PrimaryKeyConstraint('music_id', 'instrument_id')
    )
    op.drop_table('music_instrument')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_instrument',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('music_id', sa.INTEGER(), nullable=True),
    sa.Column('instrument_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('musicinstrument')
    # ### end Alembic commands ###
