"""music table

Revision ID: 837d098f5317
Revises: 
Create Date: 2018-04-09 09:07:19.707435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837d098f5317'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.Column('range', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_name'), 'instrument', ['name'], unique=True)
    op.create_table('original_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style',
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('style')
    )
    op.create_table('music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=32), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=True),
    sa.Column('original_author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['original_author_id'], ['original_author.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['style.style'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_name'), 'music', ['name'], unique=False)
    op.create_table('music_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_instrument')
    op.drop_index(op.f('ix_music_name'), table_name='music')
    op.drop_table('music')
    op.drop_table('style')
    op.drop_table('original_author')
    op.drop_index(op.f('ix_instrument_name'), table_name='instrument')
    op.drop_table('instrument')
    # ### end Alembic commands ###
